from pathlib import Path


def patch_app():
    p=Path('app.py'); s=p.read_text()
    old='''def kalshi_numeric_target(market):\n    """Return the numeric settlement strike exactly as Kalshi exposes it."""\n    if not isinstance(market, dict):\n        return np.nan\n    strike_type = str(market.get("strike_type") or "").lower()\n    preferred = (\n        ("cap_strike", "floor_strike")\n        if strike_type in {"less", "less_equal", "less-than", "less_than"}\n        else ("floor_strike", "cap_strike")\n    )\n    for key in preferred:\n        value = safe_float(market.get(key))\n        if pd.notna(value) and value > 0:\n            return float(value)\n    return np.nan\n'''
    new='''def kalshi_numeric_target(market):\n    """Return the displayed KXBTC15M Target Price, with strike fields as fallback."""\n    if not isinstance(market, dict):\n        return np.nan\n    # KXBTC15M is an up/down contract. Kalshi exposes the user-facing opening\n    # reference as `Target Price: $xx,xxx.xx` in the subtitle fields. That is\n    # the number the dashboard must match. Do not substitute a threshold field\n    # when the explicit target label is present.\n    for key in ("yes_sub_title", "subtitle", "title"):\n        text = str(market.get(key) or "")\n        match = re.search(r"Target\\s*Price\\s*:\\s*\\$?([0-9][0-9,]*(?:\\.[0-9]+)?)", text, re.I)\n        if match:\n            value = safe_float(match.group(1).replace(",", ""))\n            if pd.notna(value) and value > 0:\n                return float(value)\n    strike_type = str(market.get("strike_type") or "").lower()\n    preferred = (("cap_strike", "floor_strike") if strike_type in {"less", "less_equal", "less-than", "less_than"} else ("floor_strike", "cap_strike"))\n    for key in preferred:\n        value = safe_float(market.get(key))\n        if pd.notna(value) and value > 0:\n            return float(value)\n    return np.nan\n'''
    if old not in s: raise SystemExit('python target helper anchor missing')
    s=s.replace(old,new,1)
    oldjs='''        function numericKalshiTarget(m) {{\n            if (!m) return NaN;\n            const strikeType = String(m.strike_type || "").toLowerCase();\n            const preferCap = ["less", "less_equal", "less-than", "less_than"].includes(strikeType);\n            const first = Number(preferCap ? m.cap_strike : m.floor_strike);\n            const second = Number(preferCap ? m.floor_strike : m.cap_strike);\n            if (Number.isFinite(first) && first > 0) return first;\n            if (Number.isFinite(second) && second > 0) return second;\n            return NaN;\n        }}'''
    newjs='''        function numericKalshiTarget(m) {{\n            if (!m) return NaN;\n            for (const key of ["yes_sub_title", "subtitle", "title"]) {{\n                const text = String(m[key] || "");\n                const hit = text.match(/Target\\s*Price\\s*:\\s*\\$?([0-9][0-9,]*(?:\\.[0-9]+)?)/i);\n                if (hit) {{\n                    const explicitTarget = Number(hit[1].replace(/,/g, ""));\n                    if (Number.isFinite(explicitTarget) && explicitTarget > 0) return explicitTarget;\n                }}\n            }}\n            const strikeType = String(m.strike_type || "").toLowerCase();\n            const preferCap = ["less", "less_equal", "less-than", "less_than"].includes(strikeType);\n            const first = Number(preferCap ? m.cap_strike : m.floor_strike);\n            const second = Number(preferCap ? m.floor_strike : m.cap_strike);\n            if (Number.isFinite(first) && first > 0) return first;\n            if (Number.isFinite(second) && second > 0) return second;\n            return NaN;\n        }}'''
    if oldjs not in s: raise SystemExit('browser target helper anchor missing')
    s=s.replace(oldjs,newjs,1)
    p.write_text(s)


def patch_learner():
    p=Path('learner.py'); s=p.read_text()
    s=s.replace('import os\nimport time\n','import os\nimport re\nimport time\n',1)
    old='''def strike(market):\n    if not isinstance(market, dict):\n        return None\n    strike_type = str(market.get("strike_type") or "").lower()\n    keys = ("cap_strike", "floor_strike") if strike_type in {"less", "less_equal", "less-than", "less_than"} else ("floor_strike", "cap_strike")\n    for key in keys:\n        try:\n            value = float(market.get(key))\n            if math.isfinite(value) and value > 0:\n                return value\n        except Exception:\n            pass\n    return None\n'''
    new='''def strike(market):\n    if not isinstance(market, dict):\n        return None\n    for key in ("yes_sub_title", "subtitle", "title"):\n        text = str(market.get(key) or "")\n        match = re.search(r"Target\\s*Price\\s*:\\s*\\$?([0-9][0-9,]*(?:\\.[0-9]+)?)", text, re.I)\n        if match:\n            try:\n                value = float(match.group(1).replace(",", ""))\n                if math.isfinite(value) and value > 0:\n                    return value\n            except Exception:\n                pass\n    strike_type = str(market.get("strike_type") or "").lower()\n    keys = ("cap_strike", "floor_strike") if strike_type in {"less", "less_equal", "less-than", "less_than"} else ("floor_strike", "cap_strike")\n    for key in keys:\n        try:\n            value = float(market.get(key))\n            if math.isfinite(value) and value > 0:\n                return value\n        except Exception:\n            pass\n    return None\n'''
    if old not in s: raise SystemExit('learner target helper anchor missing')
    s=s.replace(old,new,1); p.write_text(s)

patch_app(); patch_learner()
print('Kalshi target repair applied to server, browser chart, and 24/7 learner.')
